-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- journal
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'journal' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'journal');
  END LOOP;
END
$authz$;
ALTER TABLE public."journal" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."journal" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('accounting_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."journal" FOR INSERT WITH CHECK (("status" in ('Draft', 'Posted') AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('accounting_create'))::text[])));
CREATE POLICY "UPDATE" ON "public"."journal" FOR UPDATE USING (("status" in ('Draft', 'Posted') AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('accounting_update'))::text[]))) WITH CHECK (("status" in ('Draft', 'Posted', 'Reversed') AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('accounting_update'))::text[])));
CREATE POLICY "DELETE" ON "public"."journal" FOR DELETE USING (("status" = 'Draft' AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('accounting_delete'))::text[])));

-- journalLine
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'journalLine' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'journalLine');
  END LOOP;
END
$authz$;
ALTER TABLE public."journalLine" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."journalLine" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('accounting_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."journalLine" FOR INSERT WITH CHECK (("companyId" = ANY ((SELECT get_companies_with_employee_permission('accounting_create'))::text[]) AND EXISTS (SELECT 1 FROM "public"."journal" p WHERE "p"."id" = "journalLine"."journalId" AND "status" in ('Draft', 'Posted'))));
CREATE POLICY "UPDATE" ON "public"."journalLine" FOR UPDATE USING (("companyId" = ANY ((SELECT get_companies_with_employee_permission('accounting_update'))::text[]) AND EXISTS (SELECT 1 FROM "public"."journal" p WHERE "p"."id" = "journalLine"."journalId" AND "status" = 'Draft')));
CREATE POLICY "DELETE" ON "public"."journalLine" FOR DELETE USING (("companyId" = ANY ((SELECT get_companies_with_employee_permission('accounting_delete'))::text[]) AND EXISTS (SELECT 1 FROM "public"."journal" p WHERE "p"."id" = "journalLine"."journalId" AND "status" = 'Draft')));
