-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

CREATE OR REPLACE FUNCTION public.queue_kanban_level_checks()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  touched JSONB;
  target RECORD;
  below TEXT[];
BEGIN
  -- A seed, a restore or a test fixture loads ledger rows in bulk.
  -- The hourly sweep (util.sweep_kanban_levels) covers those.
  IF current_setting('app.sync_in_progress', true) = 'true' THEN
    RETURN NULL;
  END IF;

  -- Only batched_new exists on INSERT and only batched_old on DELETE.
  IF TG_OP = 'DELETE' THEN
    SELECT jsonb_agg(DISTINCT jsonb_build_object(
      'companyId', "companyId", 'itemId', "itemId", 'storageUnitId', "storageUnitId"))
    INTO touched
    FROM batched_old
    WHERE "storageUnitId" IS NOT NULL;
  ELSE
    SELECT jsonb_agg(DISTINCT jsonb_build_object(
      'companyId', "companyId", 'itemId', "itemId", 'storageUnitId', "storageUnitId"))
    INTO touched
    FROM batched_new
    WHERE "storageUnitId" IS NOT NULL;
  END IF;

  IF touched IS NULL THEN
    RETURN NULL;
  END IF;

  FOR target IN
    SELECT k."companyId", array_agg(DISTINCT k."id") AS "kanbanIds"
    FROM jsonb_to_recordset(touched) AS t("companyId" TEXT, "itemId" TEXT, "storageUnitId" TEXT)
    JOIN "kanban" k
      ON k."companyId" = t."companyId"
     AND k."itemId" = t."itemId"
     AND k."storageUnitId" = t."storageUnitId"
    WHERE k."replenishmentSystem" = 'Transfer'
      AND k."replenishmentLevel" IS NOT NULL
    GROUP BY k."companyId"
  LOOP
    SELECT array_agg(p."kanbanId" ORDER BY p."kanbanId")
    INTO below
    FROM get_kanban_projected_quantities(target."companyId", target."kanbanIds") p
    WHERE p."projectedQuantity" < p."replenishmentLevel";

    IF below IS NOT NULL THEN
      PERFORM util.send_inngest_event(
        'carbon/kanban.level-check',
        jsonb_build_object('companyId', target."companyId", 'kanbanIds', to_jsonb(below))
      );
    END IF;
  END LOOP;

  RETURN NULL;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_kanban_level_check(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  is_below BOOLEAN;
BEGIN
  IF current_setting('app.sync_in_progress', true) = 'true' THEN
    RETURN;
  END IF;

  IF p_operation NOT IN ('INSERT', 'UPDATE') THEN
    RETURN;
  END IF;

  IF (p_new->>'replenishmentSystem') IS DISTINCT FROM 'Transfer'
    OR (p_new->>'replenishmentLevel') IS NULL
  THEN
    RETURN;
  END IF;

  -- An UPDATE that changes nothing the level check reads does not re-check.
  IF p_operation = 'UPDATE'
    AND (p_new->'replenishmentLevel') IS NOT DISTINCT FROM (p_old->'replenishmentLevel')
    AND (p_new->'replenishmentSystem') IS NOT DISTINCT FROM (p_old->'replenishmentSystem')
    AND (p_new->'quantity') IS NOT DISTINCT FROM (p_old->'quantity')
    AND (p_new->'itemId') IS NOT DISTINCT FROM (p_old->'itemId')
    AND (p_new->'locationId') IS NOT DISTINCT FROM (p_old->'locationId')
    AND (p_new->'storageUnitId') IS NOT DISTINCT FROM (p_old->'storageUnitId')
    AND (p_new->'fromStorageUnitId') IS NOT DISTINCT FROM (p_old->'fromStorageUnitId')
  THEN
    RETURN;
  END IF;

  SELECT EXISTS (
    SELECT 1
    FROM get_kanban_projected_quantities(p_new->>'companyId', ARRAY[p_new->>'id']) p
    WHERE p."projectedQuantity" < p."replenishmentLevel"
  ) INTO is_below;

  IF is_below THEN
    PERFORM util.send_inngest_event(
      'carbon/kanban.level-check',
      jsonb_build_object('companyId', p_new->>'companyId', 'kanbanIds', jsonb_build_array(p_new->>'id'))
    );
  END IF;
END;
$function$;

-- event triggers (packages/database/src/event-system/attachments.ts)
SET lock_timeout = '5s';
SELECT set_event_triggers('itemLedger', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['apply_item_stock_quantities', 'broadcast_table_changes', 'queue_kanban_level_checks']::text[]);
SELECT set_event_triggers('kanban', ARRAY[]::text[], ARRAY['sync_kanban_level_check']::text[], false, ARRAY[]::text[]);
RESET lock_timeout;
