-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- customerContractLedgerEntry
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'customerContractLedgerEntry' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'customerContractLedgerEntry');
  END LOOP;
END
$authz$;
ALTER TABLE public."customerContractLedgerEntry" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."customerContractLedgerEntry" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."customerContractLedgerEntry" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."customerContractLedgerEntry" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."customerContractLedgerEntry" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_delete'))::text[]));

-- customerContractRevenue
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'customerContractRevenue' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'customerContractRevenue');
  END LOOP;
END
$authz$;
ALTER TABLE public."customerContractRevenue" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."customerContractRevenue" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."customerContractRevenue" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."customerContractRevenue" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."customerContractRevenue" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_delete'))::text[]));
