-- Wrap auth.uid() in RLS policy predicates in (SELECT ...) so Postgres evaluates it once
-- per statement (InitPlan) instead of once per row -- the Supabase-documented RLS perf
-- pattern. Predicate-equivalent (row visibility unchanged). Generated by
-- 'pgrls fix --rule PERF001' and verified (PERF001 -> 0). Refs #964.

-- [PERF001] Wrap auth function call(s) in policy 'DELETE' on public.document so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "DELETE" ON public.document
    USING ("companyId" = ANY(CAST((SELECT get_companies_with_permission(CAST('documents_delete' AS text)) AS get_companies_with_permission) AS text[])) AND (has_valid_api_key_for_company("companyId") OR (groups_for_user(CAST((SELECT auth.uid()) AS text)) && "writeGroups") = TRUE));

-- [PERF001] Wrap auth function call(s) in policy 'SELECT' on public.document so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "SELECT" ON public.document
    USING ("companyId" = ANY(CAST((SELECT get_companies_with_permission(CAST('documents_view' AS text)) AS get_companies_with_permission) AS text[])) AND (has_valid_api_key_for_company("companyId") OR (groups_for_user(CAST((SELECT auth.uid()) AS text)) && "readGroups") = TRUE));

-- [PERF001] Wrap auth function call(s) in policy 'UPDATE' on public.document so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "UPDATE" ON public.document
    USING ("companyId" = ANY(CAST((SELECT get_companies_with_permission(CAST('documents_update' AS text)) AS get_companies_with_permission) AS text[])) AND (has_valid_api_key_for_company("companyId") OR (groups_for_user(CAST((SELECT auth.uid()) AS text)) && "writeGroups") = TRUE));

-- [PERF001] Wrap auth function call(s) in policy 'Authenticated users can view industries' on public.industry so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Authenticated users can view industries" ON public.industry
    USING ((SELECT auth.role()) = CAST('authenticated' AS text));

-- [PERF001] Wrap auth function call(s) in policy 'SELECT' on public.notification so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "SELECT" ON public.notification
    USING ("userId" = CAST((SELECT auth.uid()) AS text));

-- [PERF001] Wrap auth function call(s) in policy 'UPDATE' on public.notification so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "UPDATE" ON public.notification
    USING ("userId" = CAST((SELECT auth.uid()) AS text));

-- [PERF001] Wrap auth function call(s) in policy 'DELETE' on public.passkeyCredential so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "DELETE" ON public."passkeyCredential"
    USING (CAST((SELECT auth.uid()) AS text) = "userId");

-- [PERF001] Wrap auth function call(s) in policy 'SELECT' on public.passkeyCredential so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "SELECT" ON public."passkeyCredential"
    USING (CAST((SELECT auth.uid()) AS text) = "userId");

-- [PERF001] Wrap auth function call(s) in policy 'UPDATE' on public.passkeyCredential so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "UPDATE" ON public."passkeyCredential"
    USING (CAST((SELECT auth.uid()) AS text) = "userId");

-- [PERF001] Wrap auth function call(s) in policy 'SELECT' on public.timeCardEntry so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "SELECT" ON public."timeCardEntry"
    USING (("employeeId" = CAST((SELECT auth.uid()) AS text) AND "companyId" = ANY(CAST((SELECT get_companies_with_employee_role() AS get_companies_with_employee_role) AS text[]))) OR "companyId" = ANY(CAST((SELECT get_companies_with_employee_permission(CAST('people_view' AS text)) AS get_companies_with_employee_permission) AS text[])));

-- [PERF001] Wrap auth function call(s) in policy 'UPDATE' on public.timeCardEntry so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "UPDATE" ON public."timeCardEntry"
    USING (("employeeId" = CAST((SELECT auth.uid()) AS text) AND "companyId" = ANY(CAST((SELECT get_companies_with_employee_role() AS get_companies_with_employee_role) AS text[]))) OR "companyId" = ANY(CAST((SELECT get_companies_with_employee_permission(CAST('people_update' AS text)) AS get_companies_with_employee_permission) AS text[])));

-- [PERF001] Wrap auth function call(s) in policy 'DELETE' on public.userModulePreference so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "DELETE" ON public."userModulePreference"
    USING ("userId" = CAST((SELECT auth.uid()) AS text));

-- [PERF001] Wrap auth function call(s) in policy 'SELECT' on public.userModulePreference so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "SELECT" ON public."userModulePreference"
    USING ("userId" = CAST((SELECT auth.uid()) AS text));

-- [PERF001] Wrap auth function call(s) in policy 'UPDATE' on public.userModulePreference so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "UPDATE" ON public."userModulePreference"
    USING ("userId" = CAST((SELECT auth.uid()) AS text));
