-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- customerContract
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'customerContract' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'customerContract');
  END LOOP;
END
$authz$;
ALTER TABLE public."customerContract" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."customerContract" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."customerContract" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."customerContract" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."customerContract" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_delete'))::text[]));

-- customerContractAmendment
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'customerContractAmendment' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'customerContractAmendment');
  END LOOP;
END
$authz$;
ALTER TABLE public."customerContractAmendment" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."customerContractAmendment" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."customerContractAmendment" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."customerContractAmendment" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."customerContractAmendment" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_delete'))::text[]));

-- customerContractInvoice
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'customerContractInvoice' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'customerContractInvoice');
  END LOOP;
END
$authz$;
ALTER TABLE public."customerContractInvoice" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."customerContractInvoice" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."customerContractInvoice" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."customerContractInvoice" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."customerContractInvoice" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_delete'))::text[]));

-- customerContractInvoiceLine
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'customerContractInvoiceLine' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'customerContractInvoiceLine');
  END LOOP;
END
$authz$;
ALTER TABLE public."customerContractInvoiceLine" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."customerContractInvoiceLine" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."customerContractInvoiceLine" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."customerContractInvoiceLine" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."customerContractInvoiceLine" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_delete'))::text[]));

-- customerContractLine
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'customerContractLine' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'customerContractLine');
  END LOOP;
END
$authz$;
ALTER TABLE public."customerContractLine" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."customerContractLine" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."customerContractLine" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."customerContractLine" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."customerContractLine" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_delete'))::text[]));
