-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- event triggers (packages/database/src/event-system/attachments.ts)
SET lock_timeout = '5s';
SELECT set_event_triggers('changeOrder', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('changeOrderActionTask', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('changeOrderAffectedItem', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('changeOrderSupersession', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
RESET lock_timeout;
