-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- certificate
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'certificate' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'certificate');
  END LOOP;
END
$authz$;
ALTER TABLE public."certificate" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."certificate" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]));
CREATE POLICY "INSERT" ON "public"."certificate" FOR INSERT WITH CHECK (("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_create'))::text[]) OR "companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[])));
CREATE POLICY "UPDATE" ON "public"."certificate" FOR UPDATE USING (("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_update'))::text[]) OR "companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[])));
CREATE POLICY "DELETE" ON "public"."certificate" FOR DELETE USING (("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_delete'))::text[]) OR "companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[])));

-- certificateOfConformance
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'certificateOfConformance' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'certificateOfConformance');
  END LOOP;
END
$authz$;
ALTER TABLE public."certificateOfConformance" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."certificateOfConformance" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]));
CREATE POLICY "INSERT" ON "public"."certificateOfConformance" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_update'))::text[]));
CREATE POLICY "UPDATE" ON "public"."certificateOfConformance" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."certificateOfConformance" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_delete'))::text[]));

-- complianceStatement
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'complianceStatement' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'complianceStatement');
  END LOOP;
END
$authz$;
ALTER TABLE public."complianceStatement" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."complianceStatement" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]));
CREATE POLICY "INSERT" ON "public"."complianceStatement" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."complianceStatement" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."complianceStatement" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- complianceStatementAssignment
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'complianceStatementAssignment' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'complianceStatementAssignment');
  END LOOP;
END
$authz$;
ALTER TABLE public."complianceStatementAssignment" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."complianceStatementAssignment" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]));
CREATE POLICY "INSERT" ON "public"."complianceStatementAssignment" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."complianceStatementAssignment" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."complianceStatementAssignment" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- firstArticleInspection
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'firstArticleInspection' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'firstArticleInspection');
  END LOOP;
END
$authz$;
ALTER TABLE public."firstArticleInspection" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."firstArticleInspection" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]));
CREATE POLICY "INSERT" ON "public"."firstArticleInspection" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."firstArticleInspection" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."firstArticleInspection" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));

-- firstArticleInspectionProduct
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'firstArticleInspectionProduct' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'firstArticleInspectionProduct');
  END LOOP;
END
$authz$;
ALTER TABLE public."firstArticleInspectionProduct" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."firstArticleInspectionProduct" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]));
CREATE POLICY "INSERT" ON "public"."firstArticleInspectionProduct" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."firstArticleInspectionProduct" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."firstArticleInspectionProduct" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('quality_delete'))::text[]));
