-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- customerItemRentalRate
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'customerItemRentalRate' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'customerItemRentalRate');
  END LOOP;
END
$authz$;
ALTER TABLE public."customerItemRentalRate" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."customerItemRentalRate" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."customerItemRentalRate" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."customerItemRentalRate" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."customerItemRentalRate" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('sales_delete'))::text[]));
