-- Tombstone: this branch-only follow-up is intentionally inert.
--
-- The corrected, tenant-composite policies and database mutation guards are
-- installed by 20260911041045_reconcile-ramp-card-transactions.sql for both
-- clean and previously-applied branch databases.
