-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

CREATE OR REPLACE FUNCTION public.create_event_system_subscription(p_name text, p_table text, p_company_id text, p_operations text[], p_handler_type text, p_config jsonb DEFAULT '{}'::jsonb, p_filter jsonb DEFAULT '{}'::jsonb, p_active boolean DEFAULT true)
 RETURNS TABLE(id text, name text, "handlerType" text, "table" text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  IF NOT util.can_manage_event_subscription(p_company_id, p_handler_type) THEN
    RAISE EXCEPTION 'Not authorized to manage % event subscriptions for company %', p_handler_type, p_company_id
      USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  INSERT INTO "eventSystemSubscription" (
    "name", "table", "companyId", "operations",
    "handlerType", "config", "filter", "active"
  )
  VALUES (
    p_name, p_table, p_company_id, p_operations,
    p_handler_type, p_config, p_filter, p_active
  )
  ON CONFLICT ON CONSTRAINT "unique_subscription_name_per_company"
  DO UPDATE SET
    "operations" = EXCLUDED."operations",
    "filter" = EXCLUDED."filter",
    "handlerType" = EXCLUDED."handlerType",
    "config" = EXCLUDED."config",
    "active" = EXCLUDED."active"
  -- Replacing a subscription also needs the right to manage what it was.
  WHERE util.can_manage_event_subscription(
    p_company_id,
    "eventSystemSubscription"."handlerType"
  )
  RETURNING
    "eventSystemSubscription"."id",
    "eventSystemSubscription"."name",
    "eventSystemSubscription"."handlerType",
    "eventSystemSubscription"."table";

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Not authorized to replace event subscription "%" for company %', p_name, p_company_id
      USING ERRCODE = '42501';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.insert_audit_log_batch(p_company_id text, p_entries jsonb[])
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  tbl_name TEXT;
  inserted_count INTEGER := 0;
BEGIN
  PERFORM assert_audit_log_access(p_company_id, NULL);

  tbl_name := 'auditLog_' || p_company_id;

  PERFORM create_audit_log_table(p_company_id);

  -- createdAt is the entry's own (the original event time) when it has one.
  -- clock_timestamp() is evaluated per row, so the rest still get distinct
  -- values rather than sharing NOW().
  EXECUTE format('
    INSERT INTO %I ("tableName", "entityType", "entityId", "recordId", "operation", "actorId", "diff", "metadata", "createdAt")
    SELECT
      e->>''tableName'',
      e->>''entityType'',
      e->>''entityId'',
      e->>''recordId'',
      e->>''operation'',
      e->>''actorId'',
      NULLIF(e->''diff'', ''null''::jsonb),
      NULLIF(e->''metadata'', ''null''::jsonb),
      COALESCE((e->>''createdAt'')::TIMESTAMPTZ, clock_timestamp())
    FROM unnest($1) AS e
  ', tbl_name)
  USING p_entries;
  GET DIAGNOSTICS inserted_count = ROW_COUNT;

  RETURN inserted_count;
END;
$function$;
