-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- userDashboardPreference
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'userDashboardPreference' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'userDashboardPreference');
  END LOOP;
END
$authz$;
ALTER TABLE public."userDashboardPreference" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."userDashboardPreference" FOR SELECT USING (("userId" = ((SELECT auth.uid()))::text AND "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[])));
CREATE POLICY "INSERT" ON "public"."userDashboardPreference" FOR INSERT WITH CHECK (("userId" = ((SELECT auth.uid()))::text AND "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[])));
CREATE POLICY "UPDATE" ON "public"."userDashboardPreference" FOR UPDATE USING (("userId" = ((SELECT auth.uid()))::text AND "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[])));
CREATE POLICY "DELETE" ON "public"."userDashboardPreference" FOR DELETE USING (("userId" = ((SELECT auth.uid()))::text AND "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[])));

-- userDashboardWidget
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'userDashboardWidget' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'userDashboardWidget');
  END LOOP;
END
$authz$;
ALTER TABLE public."userDashboardWidget" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."userDashboardWidget" FOR SELECT USING (("userId" = ((SELECT auth.uid()))::text AND "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[])));
CREATE POLICY "INSERT" ON "public"."userDashboardWidget" FOR INSERT WITH CHECK (("userId" = ((SELECT auth.uid()))::text AND "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[])));
CREATE POLICY "UPDATE" ON "public"."userDashboardWidget" FOR UPDATE USING (("userId" = ((SELECT auth.uid()))::text AND "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[])));
CREATE POLICY "DELETE" ON "public"."userDashboardWidget" FOR DELETE USING (("userId" = ((SELECT auth.uid()))::text AND "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[])));
