-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- changeOrderImpactDecision
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'changeOrderImpactDecision' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'changeOrderImpactDecision');
  END LOOP;
END
$authz$;
ALTER TABLE public."changeOrderImpactDecision" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."changeOrderImpactDecision" FOR SELECT USING ((("companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_view'))::text[]) AND (("targetType" = 'purchaseOrderLine' AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('purchasing_view'))::text[])) OR ("targetType" in ('job', 'jobMaterial') AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('production_view'))::text[])))) AND EXISTS (SELECT 1 FROM "public"."changeOrder" p WHERE "p"."id" = "changeOrderImpactDecision"."changeNoticeId" AND "p"."companyId" = "changeOrderImpactDecision"."companyId" AND "p"."companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_view'))::text[]))));

-- changeOrderImpactDecisionActionTask
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'changeOrderImpactDecisionActionTask' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'changeOrderImpactDecisionActionTask');
  END LOOP;
END
$authz$;
ALTER TABLE public."changeOrderImpactDecisionActionTask" ENABLE ROW LEVEL SECURITY;

    CREATE POLICY "SELECT" ON "public"."changeOrderImpactDecisionActionTask" FOR SELECT USING (
      "companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_view'))::text[])
      AND EXISTS (
        SELECT 1 FROM "changeOrderImpactDecision" d
        JOIN "changeOrderActionTask" task
          ON task."changeOrderId" = d."changeNoticeId"
         AND task."companyId" = d."companyId"
        WHERE d."id" = "changeOrderImpactDecisionActionTask"."decisionId"
          AND d."companyId" = "changeOrderImpactDecisionActionTask"."companyId"
          AND task."id" = "changeOrderImpactDecisionActionTask"."actionTaskId"
          AND d."companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_view'))::text[])
          AND (
            (d."targetType" = 'purchaseOrderLine'
              AND d."companyId" = ANY ((SELECT get_companies_with_employee_permission('purchasing_view'))::text[]))
            OR
            (d."targetType" IN ('job', 'jobMaterial')
              AND d."companyId" = ANY ((SELECT get_companies_with_employee_permission('production_view'))::text[]))
          )
      )
    );
    

-- changeOrderImpactDecisionAffectedItem
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'changeOrderImpactDecisionAffectedItem' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'changeOrderImpactDecisionAffectedItem');
  END LOOP;
END
$authz$;
ALTER TABLE public."changeOrderImpactDecisionAffectedItem" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."changeOrderImpactDecisionAffectedItem" FOR SELECT USING (("companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_view'))::text[]) AND EXISTS (SELECT 1 FROM "public"."changeOrderImpactDecision" p WHERE "p"."id" = "changeOrderImpactDecisionAffectedItem"."decisionId" AND "p"."companyId" = "changeOrderImpactDecisionAffectedItem"."companyId" AND ("companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_view'))::text[]) AND (("targetType" = 'purchaseOrderLine' AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('purchasing_view'))::text[])) OR ("targetType" in ('job', 'jobMaterial') AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('production_view'))::text[])))))));

-- changeOrderImpactDecisionHistory
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'changeOrderImpactDecisionHistory' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'changeOrderImpactDecisionHistory');
  END LOOP;
END
$authz$;
ALTER TABLE public."changeOrderImpactDecisionHistory" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."changeOrderImpactDecisionHistory" FOR SELECT USING (("companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_view'))::text[]) AND EXISTS (SELECT 1 FROM "public"."changeOrderImpactDecision" p WHERE "p"."id" = "changeOrderImpactDecisionHistory"."decisionId" AND "p"."companyId" = "changeOrderImpactDecisionHistory"."companyId" AND ("companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_view'))::text[]) AND (("targetType" = 'purchaseOrderLine' AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('purchasing_view'))::text[])) OR ("targetType" in ('job', 'jobMaterial') AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('production_view'))::text[])))))));
