-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

CREATE OR REPLACE FUNCTION util.document_sequence_number(p_value text, p_prefix text, p_suffix text, p_size integer)
 RETURNS bigint
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE
  v_digits text;
BEGIN
  -- The number get_next_sequence would have formatted as p_value, or NULL when
  -- p_value is not in the sequence's format (a custom id such as "ACME-1").
  v_digits := substring(p_value FROM util.document_sequence_pattern(p_prefix, p_suffix, p_size));

  IF v_digits IS NULL OR length(v_digits) > 18 THEN
    RETURN NULL;
  END IF;

  RETURN v_digits::bigint;
END;
$function$;

CREATE OR REPLACE FUNCTION util.document_sequence_pattern(p_prefix text, p_suffix text, p_size integer)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE
  v_prefix text;
  v_suffix text;
BEGIN
  -- A regular expression matching what get_next_sequence (and its TypeScript
  -- twin, getNextSequence in @carbon/database/sequence) formats for a
  -- sequence, capturing the number. Date tokens match any date: the counter
  -- does not reset per period. get_next_sequence pads to p_size, so a shorter
  -- number is never one it issues.
  v_prefix := regexp_replace(COALESCE(p_prefix, ''), '([.^$*+?()\[\]{}|\\])', '\\\1', 'g');
  v_prefix := replace(v_prefix, '%\{yyyy\}', '[0-9]{4}');
  v_prefix := replace(v_prefix, '%\{yy\}', '[0-9]{2}');
  v_prefix := replace(v_prefix, '%\{mm\}', '[0-9]{2}');
  v_prefix := replace(v_prefix, '%\{ww\}', '[0-9]{2}');
  v_prefix := replace(v_prefix, '%\{dd\}', '[0-9]{2}');
  v_prefix := replace(v_prefix, '%\{hh\}', '[0-9]{2}');
  v_prefix := replace(v_prefix, '%\{ss\}', '[0-9]{2}');

  v_suffix := regexp_replace(COALESCE(p_suffix, ''), '([.^$*+?()\[\]{}|\\])', '\\\1', 'g');
  v_suffix := replace(v_suffix, '%\{yyyy\}', '[0-9]{4}');
  v_suffix := replace(v_suffix, '%\{yy\}', '[0-9]{2}');
  v_suffix := replace(v_suffix, '%\{mm\}', '[0-9]{2}');
  v_suffix := replace(v_suffix, '%\{ww\}', '[0-9]{2}');
  v_suffix := replace(v_suffix, '%\{dd\}', '[0-9]{2}');
  v_suffix := replace(v_suffix, '%\{hh\}', '[0-9]{2}');
  v_suffix := replace(v_suffix, '%\{ss\}', '[0-9]{2}');

  RETURN '^' || v_prefix || '([0-9]{' || COALESCE(p_size, 4) || ',})' || v_suffix || '$';
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_advance_document_sequence(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_column text;
  v_sequence text;
  v_value text;
BEGIN
  -- A document saved with a number in its sequence's format (typed by hand,
  -- sent through the API or MCP, imported) moves the counter past it, so
  -- get_next_sequence never hands that number out again.
  IF p_operation NOT IN ('INSERT', 'UPDATE') THEN
    RETURN;
  END IF;

  -- A new numbered table is added here and attached in attachments.ts.
  v_column := CASE p_table
    WHEN 'changeOrder' THEN 'changeOrderId'
    WHEN 'customer' THEN 'readableId'
    WHEN 'customerContract' THEN 'customerContractId'
    WHEN 'depreciationRun' THEN 'depreciationRunId'
    WHEN 'fixedAsset' THEN 'fixedAssetId'
    WHEN 'gauge' THEN 'gaugeId'
    WHEN 'inventoryCount' THEN 'inventoryCountId'
    WHEN 'job' THEN 'jobId'
    WHEN 'journal' THEN 'journalEntryId'
    WHEN 'maintenanceDispatch' THEN 'maintenanceDispatchId'
    WHEN 'memo' THEN 'memoId'
    WHEN 'nonConformance' THEN 'nonConformanceId'
    WHEN 'payment' THEN 'paymentId'
    WHEN 'pickingList' THEN 'pickingListId'
    WHEN 'purchaseInvoice' THEN 'invoiceId'
    WHEN 'purchaseOrder' THEN 'purchaseOrderId'
    WHEN 'purchaseReturnOrder' THEN 'purchaseReturnOrderId'
    WHEN 'purchasingRfq' THEN 'rfqId'
    WHEN 'quote' THEN 'quoteId'
    WHEN 'receipt' THEN 'receiptId'
    WHEN 'rentalAgreement' THEN 'rentalAgreementId'
    WHEN 'salesInvoice' THEN 'invoiceId'
    WHEN 'salesOrder' THEN 'salesOrderId'
    WHEN 'salesReturnOrder' THEN 'salesReturnOrderId'
    WHEN 'salesRfq' THEN 'rfqId'
    WHEN 'shipment' THEN 'shipmentId'
    WHEN 'stockTransfer' THEN 'stockTransferId'
    WHEN 'supplier' THEN 'readableId'
    WHEN 'supplierQuote' THEN 'supplierQuoteId'
    WHEN 'warehouseTransfer' THEN 'transferId'
  END;

  IF v_column IS NULL THEN
    RETURN;
  END IF;

  v_value := p_new->>v_column;
  IF v_value IS NULL
    OR (p_operation = 'UPDATE' AND v_value IS NOT DISTINCT FROM p_old->>v_column)
  THEN
    RETURN;
  END IF;

  -- The sequence is named after its table, except these.
  v_sequence := CASE
    WHEN p_table = 'journal' THEN 'journalEntry'
    WHEN p_table = 'memo' AND p_new->>'direction' = 'Debit' THEN 'debitMemo'
    WHEN p_table = 'memo' THEN 'creditMemo'
    ELSE p_table
  END;

  UPDATE "sequence"
  SET "next" = util.document_sequence_number(v_value, "prefix", "suffix", "size")::integer,
      "updatedBy" = 'system'
  WHERE "table" = v_sequence
    AND "companyId" = p_new->>'companyId'
    AND util.document_sequence_number(v_value, "prefix", "suffix", "size")
      BETWEEN "next"::bigint + 1 AND 2147483647;
END;
$function$;

-- event triggers (packages/database/src/event-system/attachments.ts)
SET lock_timeout = '5s';
SELECT set_event_triggers('changeOrder', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('customer', ARRAY['sync_update_customer_type_group']::text[], ARRAY['sync_create_customer_entries', 'sync_create_customer_org_group', 'sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes', 'log_table_changes']::text[]);
SELECT set_event_triggers('customerContract', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], false, ARRAY[]::text[]);
SELECT set_event_triggers('depreciationRun', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('fixedAsset', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('gauge', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('inventoryCount', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('job', ARRAY['sync_job_complete_or_canceled']::text[], ARRAY['sync_insert_job_make_method', 'sync_job_recompute_service_line', 'sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('journal', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('maintenanceDispatch', ARRAY[]::text[], ARRAY['sync_on_maintenance_dispatch_complete', 'sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('memo', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('nonConformance', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('payment', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('pickingList', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('purchaseInvoice', ARRAY['prevent_posted_purchase_invoice_deletion']::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('purchaseOrder', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('purchaseReturnOrder', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('purchasingRfq', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('quote', ARRAY['sync_update_quote_exchange_rate']::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('receipt', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('rentalAgreement', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], false, ARRAY[]::text[]);
SELECT set_event_triggers('salesInvoice', ARRAY['prevent_posted_sales_invoice_deletion']::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('salesOrder', ARRAY['sync_update_sales_order_exchange_rate']::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('salesReturnOrder', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('salesRfq', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('shipment', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('stockTransfer', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('supplier', ARRAY['sync_update_supplier_type_group']::text[], ARRAY['sync_create_supplier_entries', 'sync_create_supplier_org_group', 'sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes', 'log_table_changes']::text[]);
SELECT set_event_triggers('supplierQuote', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('warehouseTransfer', ARRAY[]::text[], ARRAY['sync_advance_document_sequence']::text[], true, ARRAY['broadcast_table_changes']::text[]);
RESET lock_timeout;
