-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- userLogin
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'userLogin' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'userLogin');
  END LOOP;
END
$authz$;
ALTER TABLE public."userLogin" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."userLogin" FOR SELECT USING ("userId" = ((SELECT auth.uid()))::text);
