-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

CREATE OR REPLACE FUNCTION public.broadcast_table_changes()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  ignored_columns CONSTANT TEXT[] := ARRAY['updatedAt', 'updatedBy', 'embedding'];
  changed_rows TEXT;
  rec RECORD;
BEGIN
  -- Tells the company's clients which rows of this table changed (topic company:<companyId>:<table>).
  -- Statement-level (attach_statement_handler): one message per company per
  -- statement, whatever the row count. No row data leaves the database: a client
  -- re-reads what it needs through PostgREST, so table RLS still decides what it sees.
  IF TG_OP = 'UPDATE' THEN
    -- A row whose only changes are in ignored_columns drops out (the rule
    -- dispatch_event_batch applies; event-dispatch.test.ts keeps the lists equal).
    changed_rows := 'SELECT to_jsonb(n) - $1 AS c FROM batched_new n
                     EXCEPT
                     SELECT to_jsonb(o) - $1 FROM batched_old o';
  ELSIF TG_OP = 'DELETE' THEN
    changed_rows := 'SELECT to_jsonb(o) AS c FROM batched_old o';
  ELSE
    changed_rows := 'SELECT to_jsonb(n) AS c FROM batched_new n';
  END IF;

  FOR rec IN EXECUTE format(
    -- implementationHub has no companyId: its id is the company id.
    'SELECT coalesce(c->>''companyId'',
                     CASE WHEN $2::text = ''implementationHub'' THEN c->>''id'' END) AS company_id,
            count(*) AS n,
            -- itemSupersession has no id: its row belongs to the item it describes.
            jsonb_agg(coalesce(c->''id'', c->''itemId''))
              FILTER (WHERE c ? ''id'' OR c ? ''itemId'') AS ids
       FROM (%s) changed
      GROUP BY 1',
    changed_rows
  ) USING ignored_columns, TG_TABLE_NAME
  LOOP
    CONTINUE WHEN rec.company_id IS NULL;
    PERFORM realtime.send(
      jsonb_build_object(
        'table', TG_TABLE_NAME,
        'op', TG_OP,
        -- null = "many rows changed, or the table has no id: resync"
        'ids', CASE WHEN rec.n <= 100 THEN rec.ids END
      ),
      TG_OP,
      'company:' || rec.company_id || ':' || TG_TABLE_NAME,
      true
    );
  END LOOP;
  RETURN NULL;
END;
$function$;

CREATE OR REPLACE FUNCTION public.log_table_changes()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  ignored_columns CONSTANT TEXT[] := ARRAY['updatedAt', 'updatedBy', 'embedding'];
  changed_rows TEXT;
BEGIN
  -- Records which rows of this table changed, in public."tableChange", so a
  -- client that kept a copy of a list can ask "what changed since I last
  -- looked?" (table_changes_since) and re-read only those rows instead of the
  -- whole table. A broadcast tells an open tab the same thing; this is for the
  -- tab that was closed, or disconnected, when it happened.
  IF TG_OP = 'UPDATE' THEN
    -- A row whose only changes are in ignored_columns drops out (the rule
    -- dispatch_event_batch applies; event-dispatch.test.ts keeps the lists equal).
    changed_rows := 'SELECT to_jsonb(n) - $1 AS c FROM batched_new n
                     EXCEPT
                     SELECT to_jsonb(o) - $1 FROM batched_old o';
  ELSIF TG_OP = 'DELETE' THEN
    changed_rows := 'SELECT to_jsonb(o) AS c FROM batched_old o';
  ELSE
    changed_rows := 'SELECT to_jsonb(n) AS c FROM batched_new n';
  END IF;

  EXECUTE format(
    -- One log row per changed row. Past 100 rows in one statement, a single row
    -- with a null "rowId" says "this table changed a lot: read it again".
    -- itemSupersession has no id: its row belongs to the item it describes.
    'INSERT INTO public."tableChange" ("companyId", "table", "rowId")
     SELECT DISTINCT company_id, $2::text, CASE WHEN n <= 100 THEN row_id END
       FROM (
         SELECT c->>''companyId'' AS company_id,
                coalesce(c->>''id'', c->>''itemId'') AS row_id,
                count(*) OVER (PARTITION BY c->>''companyId'') AS n
           FROM (%s) changed
       ) rows
      WHERE company_id IS NOT NULL',
    changed_rows
  ) USING ignored_columns, TG_TABLE_NAME;
  RETURN NULL;
END;
$function$;

CREATE OR REPLACE FUNCTION public.log_user_changes()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
DECLARE
  ignored_columns CONSTANT TEXT[] := ARRAY['updatedAt', 'updatedBy', 'embedding'];
  changed_rows TEXT;
BEGIN
  -- A person's name and avatar live on the global "user" row, which has no
  -- company. Each company that person belongs to shows them in its people list
  -- (the employees view), so a change is logged once per company, as a change
  -- to that company's "employee" row.
  IF TG_OP = 'UPDATE' THEN
    changed_rows := 'SELECT to_jsonb(n) - $1 AS c FROM batched_new n
                     EXCEPT
                     SELECT to_jsonb(o) - $1 FROM batched_old o';
  ELSIF TG_OP = 'DELETE' THEN
    changed_rows := 'SELECT to_jsonb(o) AS c FROM batched_old o';
  ELSE
    changed_rows := 'SELECT to_jsonb(n) AS c FROM batched_new n';
  END IF;

  EXECUTE format(
    'INSERT INTO public."tableChange" ("companyId", "table", "rowId")
     SELECT DISTINCT m."companyId", ''employee'', changed.c->>''id''
       FROM (%s) changed
       JOIN public."userToCompany" m ON m."userId" = changed.c->>''id''',
    changed_rows
  ) USING ignored_columns;
  RETURN NULL;
END;
$function$;

-- tableChange
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'tableChange' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'tableChange');
  END LOOP;
END
$authz$;
ALTER TABLE public."tableChange" ENABLE ROW LEVEL SECURITY;

-- event triggers (packages/database/src/event-system/attachments.ts)
SELECT set_event_triggers('customer', ARRAY['sync_update_customer_type_group']::text[], ARRAY['sync_create_customer_entries', 'sync_create_customer_org_group']::text[], true, ARRAY['broadcast_table_changes', 'log_table_changes']::text[]);
SELECT set_event_triggers('employee', ARRAY['sync_update_employee_type_membership']::text[], ARRAY['sync_add_employee_to_type_group']::text[], true, ARRAY['broadcast_table_changes', 'log_table_changes']::text[]);
SELECT set_event_triggers('item', ARRAY[]::text[], ARRAY['sync_create_item_related_records', 'sync_create_make_method_related_records', 'sync_propagate_item_readable_id_to_tracked_entity']::text[], true, ARRAY['broadcast_table_changes', 'log_table_changes']::text[]);
SELECT set_event_triggers('itemSupersession', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes', 'log_table_changes']::text[]);
SELECT set_event_triggers('modelUpload', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes', 'log_table_changes']::text[]);
SELECT set_event_triggers('supplier', ARRAY['sync_update_supplier_type_group']::text[], ARRAY['sync_create_supplier_entries', 'sync_create_supplier_org_group']::text[], true, ARRAY['broadcast_table_changes', 'log_table_changes']::text[]);
SELECT set_event_triggers('trackedActivity', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('user', ARRAY[]::text[], ARRAY['sync_create_user_identity_group', 'sync_update_user_identity_group', 'sync_delete_user_identity_group']::text[], false, ARRAY['log_user_changes']::text[]);
