-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- pushSubscription
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'pushSubscription' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'pushSubscription');
  END LOOP;
END
$authz$;
ALTER TABLE public."pushSubscription" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."pushSubscription" FOR SELECT USING (("userId" = ((SELECT auth.uid()))::text AND "companyId" IN (SELECT "userToCompany"."companyId" FROM "public"."userToCompany" WHERE "userId" = ((SELECT auth.uid()))::text)));
CREATE POLICY "INSERT" ON "public"."pushSubscription" FOR INSERT WITH CHECK (("userId" = ((SELECT auth.uid()))::text AND "companyId" IN (SELECT "userToCompany"."companyId" FROM "public"."userToCompany" WHERE "userId" = ((SELECT auth.uid()))::text)));
CREATE POLICY "UPDATE" ON "public"."pushSubscription" FOR UPDATE USING ("userId" = ((SELECT auth.uid()))::text) WITH CHECK (("userId" = ((SELECT auth.uid()))::text AND "companyId" IN (SELECT "userToCompany"."companyId" FROM "public"."userToCompany" WHERE "userId" = ((SELECT auth.uid()))::text)));
CREATE POLICY "DELETE" ON "public"."pushSubscription" FOR DELETE USING (("userId" = ((SELECT auth.uid()))::text AND "companyId" IN (SELECT "userToCompany"."companyId" FROM "public"."userToCompany" WHERE "userId" = ((SELECT auth.uid()))::text)));
