type CountryFacts = {
  name: string;
  alpha3: string;
  eori?: boolean;
  registrationNumber?: boolean;
};

/**
 * Canonical base country map — the single place country facts live.
 * Keys are ISO-3166 alpha-2 codes matching the "country" table seed
 * (20240928155702_country-codes.sql). Derive any per-country map or
 * group from this; never hand-write a country list elsewhere.
 */
export const COUNTRY_MAP: Record<string, CountryFacts> = {
  AF: { name: "Afghanistan", alpha3: "AFG" },
  AL: { name: "Albania", alpha3: "ALB" },
  DZ: { name: "Algeria", alpha3: "DZA" },
  AD: { name: "Andorra", alpha3: "AND" },
  AO: { name: "Angola", alpha3: "AGO" },
  AG: { name: "Antigua and Barbuda", alpha3: "ATG" },
  AR: { name: "Argentina", alpha3: "ARG" },
  AM: { name: "Armenia", alpha3: "ARM" },
  AU: { name: "Australia", alpha3: "AUS" },
  AT: { name: "Austria", alpha3: "AUT", eori: true },
  AZ: { name: "Azerbaijan", alpha3: "AZE" },
  BS: { name: "Bahamas", alpha3: "BHS" },
  BH: { name: "Bahrain", alpha3: "BHR" },
  BD: { name: "Bangladesh", alpha3: "BGD" },
  BB: { name: "Barbados", alpha3: "BRB" },
  BY: { name: "Belarus", alpha3: "BLR" },
  BE: { name: "Belgium", alpha3: "BEL", eori: true },
  BZ: { name: "Belize", alpha3: "BLZ" },
  BJ: { name: "Benin", alpha3: "BEN" },
  BT: { name: "Bhutan", alpha3: "BTN" },
  BO: { name: "Bolivia", alpha3: "BOL" },
  BA: { name: "Bosnia and Herzegovina", alpha3: "BIH" },
  BW: { name: "Botswana", alpha3: "BWA" },
  BR: { name: "Brazil", alpha3: "BRA" },
  BN: { name: "Brunei", alpha3: "BRN" },
  BG: { name: "Bulgaria", alpha3: "BGR", eori: true },
  BF: { name: "Burkina Faso", alpha3: "BFA" },
  BI: { name: "Burundi", alpha3: "BDI" },
  KH: { name: "Cambodia", alpha3: "KHM" },
  CM: { name: "Cameroon", alpha3: "CMR" },
  CA: { name: "Canada", alpha3: "CAN" },
  CV: { name: "Cape Verde", alpha3: "CPV" },
  CF: { name: "Central African Republic", alpha3: "CAF" },
  TD: { name: "Chad", alpha3: "TCD" },
  CL: { name: "Chile", alpha3: "CHL" },
  CN: { name: "China", alpha3: "CHN" },
  CO: { name: "Colombia", alpha3: "COL" },
  KM: { name: "Comoros", alpha3: "COM" },
  CG: { name: "Congo", alpha3: "COG" },
  CR: { name: "Costa Rica", alpha3: "CRI" },
  HR: { name: "Croatia", alpha3: "HRV", eori: true },
  CU: { name: "Cuba", alpha3: "CUB" },
  CY: { name: "Cyprus", alpha3: "CYP", eori: true },
  CZ: { name: "Czech Republic", alpha3: "CZE", eori: true },
  CD: { name: "Democratic Republic of the Congo", alpha3: "COD" },
  DK: { name: "Denmark", alpha3: "DNK", eori: true },
  DJ: { name: "Djibouti", alpha3: "DJI" },
  DM: { name: "Dominica", alpha3: "DMA" },
  DO: { name: "Dominican Republic", alpha3: "DOM" },
  TL: { name: "East Timor", alpha3: "TLS" },
  EC: { name: "Ecuador", alpha3: "ECU" },
  EG: { name: "Egypt", alpha3: "EGY" },
  SV: { name: "El Salvador", alpha3: "SLV" },
  GQ: { name: "Equatorial Guinea", alpha3: "GNQ" },
  ER: { name: "Eritrea", alpha3: "ERI" },
  EE: { name: "Estonia", alpha3: "EST", eori: true },
  ET: { name: "Ethiopia", alpha3: "ETH" },
  FJ: { name: "Fiji", alpha3: "FJI" },
  FI: { name: "Finland", alpha3: "FIN", eori: true },
  FR: { name: "France", alpha3: "FRA", eori: true },
  GA: { name: "Gabon", alpha3: "GAB" },
  GM: { name: "Gambia", alpha3: "GMB" },
  GE: { name: "Georgia", alpha3: "GEO" },
  DE: { name: "Germany", alpha3: "DEU", eori: true },
  GH: { name: "Ghana", alpha3: "GHA" },
  GR: { name: "Greece", alpha3: "GRC", eori: true },
  GD: { name: "Grenada", alpha3: "GRD" },
  GT: { name: "Guatemala", alpha3: "GTM" },
  GN: { name: "Guinea", alpha3: "GIN" },
  GW: { name: "Guinea-Bissau", alpha3: "GNB" },
  GY: { name: "Guyana", alpha3: "GUY" },
  HT: { name: "Haiti", alpha3: "HTI" },
  HN: { name: "Honduras", alpha3: "HND" },
  HU: { name: "Hungary", alpha3: "HUN", eori: true },
  IS: { name: "Iceland", alpha3: "ISL" },
  IN: { name: "India", alpha3: "IND" },
  ID: { name: "Indonesia", alpha3: "IDN" },
  IR: { name: "Iran", alpha3: "IRN" },
  IQ: { name: "Iraq", alpha3: "IRQ" },
  IE: { name: "Ireland", alpha3: "IRL", eori: true },
  IL: { name: "Israel", alpha3: "ISR" },
  IT: { name: "Italy", alpha3: "ITA", eori: true },
  CI: { name: "Ivory Coast", alpha3: "CIV" },
  JM: { name: "Jamaica", alpha3: "JAM" },
  JP: { name: "Japan", alpha3: "JPN" },
  JO: { name: "Jordan", alpha3: "JOR" },
  KZ: { name: "Kazakhstan", alpha3: "KAZ" },
  KE: { name: "Kenya", alpha3: "KEN" },
  KI: { name: "Kiribati", alpha3: "KIR" },
  KW: { name: "Kuwait", alpha3: "KWT" },
  KG: { name: "Kyrgyzstan", alpha3: "KGZ" },
  LA: { name: "Laos", alpha3: "LAO" },
  LV: { name: "Latvia", alpha3: "LVA", eori: true },
  LB: { name: "Lebanon", alpha3: "LBN" },
  LS: { name: "Lesotho", alpha3: "LSO" },
  LR: { name: "Liberia", alpha3: "LBR" },
  LY: { name: "Libya", alpha3: "LBY" },
  LI: { name: "Liechtenstein", alpha3: "LIE" },
  LT: { name: "Lithuania", alpha3: "LTU", eori: true },
  LU: { name: "Luxembourg", alpha3: "LUX", eori: true },
  MG: { name: "Madagascar", alpha3: "MDG" },
  MW: { name: "Malawi", alpha3: "MWI" },
  MY: { name: "Malaysia", alpha3: "MYS" },
  MV: { name: "Maldives", alpha3: "MDV" },
  ML: { name: "Mali", alpha3: "MLI" },
  MT: { name: "Malta", alpha3: "MLT", eori: true },
  MH: { name: "Marshall Islands", alpha3: "MHL" },
  MR: { name: "Mauritania", alpha3: "MRT" },
  MU: { name: "Mauritius", alpha3: "MUS" },
  MX: { name: "Mexico", alpha3: "MEX" },
  FM: { name: "Micronesia", alpha3: "FSM" },
  MD: { name: "Moldova", alpha3: "MDA" },
  MC: { name: "Monaco", alpha3: "MCO" },
  MN: { name: "Mongolia", alpha3: "MNG" },
  ME: { name: "Montenegro", alpha3: "MNE" },
  MA: { name: "Morocco", alpha3: "MAR" },
  MZ: { name: "Mozambique", alpha3: "MOZ" },
  MM: { name: "Myanmar", alpha3: "MMR" },
  NA: { name: "Namibia", alpha3: "NAM" },
  NR: { name: "Nauru", alpha3: "NRU" },
  NP: { name: "Nepal", alpha3: "NPL" },
  NL: { name: "Netherlands", alpha3: "NLD", eori: true },
  NZ: { name: "New Zealand", alpha3: "NZL" },
  NI: { name: "Nicaragua", alpha3: "NIC" },
  NE: { name: "Niger", alpha3: "NER" },
  NG: { name: "Nigeria", alpha3: "NGA" },
  KP: { name: "North Korea", alpha3: "PRK" },
  MK: { name: "North Macedonia", alpha3: "MKD" },
  NO: { name: "Norway", alpha3: "NOR" },
  OM: { name: "Oman", alpha3: "OMN" },
  PK: { name: "Pakistan", alpha3: "PAK" },
  PW: { name: "Palau", alpha3: "PLW" },
  PS: { name: "Palestine", alpha3: "PSE" },
  PA: { name: "Panama", alpha3: "PAN" },
  PG: { name: "Papua New Guinea", alpha3: "PNG" },
  PY: { name: "Paraguay", alpha3: "PRY" },
  PE: { name: "Peru", alpha3: "PER" },
  PH: { name: "Philippines", alpha3: "PHL" },
  PL: { name: "Poland", alpha3: "POL", eori: true },
  PT: { name: "Portugal", alpha3: "PRT", eori: true },
  QA: { name: "Qatar", alpha3: "QAT" },
  RO: { name: "Romania", alpha3: "ROU", eori: true },
  RU: { name: "Russia", alpha3: "RUS" },
  RW: { name: "Rwanda", alpha3: "RWA" },
  KN: { name: "Saint Kitts and Nevis", alpha3: "KNA" },
  LC: { name: "Saint Lucia", alpha3: "LCA" },
  VC: { name: "Saint Vincent and the Grenadines", alpha3: "VCT" },
  WS: { name: "Samoa", alpha3: "WSM" },
  SM: { name: "San Marino", alpha3: "SMR" },
  ST: { name: "Sao Tome and Principe", alpha3: "STP" },
  SA: { name: "Saudi Arabia", alpha3: "SAU" },
  SN: { name: "Senegal", alpha3: "SEN" },
  RS: { name: "Serbia", alpha3: "SRB" },
  SC: { name: "Seychelles", alpha3: "SYC" },
  SL: { name: "Sierra Leone", alpha3: "SLE" },
  SG: { name: "Singapore", alpha3: "SGP" },
  SK: { name: "Slovakia", alpha3: "SVK", eori: true },
  SI: { name: "Slovenia", alpha3: "SVN", eori: true },
  SB: { name: "Solomon Islands", alpha3: "SLB" },
  SO: { name: "Somalia", alpha3: "SOM" },
  ZA: { name: "South Africa", alpha3: "ZAF" },
  KR: { name: "South Korea", alpha3: "KOR" },
  SS: { name: "South Sudan", alpha3: "SSD" },
  ES: { name: "Spain", alpha3: "ESP", eori: true },
  LK: { name: "Sri Lanka", alpha3: "LKA" },
  SD: { name: "Sudan", alpha3: "SDN" },
  SR: { name: "Suriname", alpha3: "SUR" },
  SE: { name: "Sweden", alpha3: "SWE", eori: true },
  CH: { name: "Switzerland", alpha3: "CHE" },
  SY: { name: "Syria", alpha3: "SYR" },
  TJ: { name: "Tajikistan", alpha3: "TJK" },
  TZ: { name: "Tanzania", alpha3: "TZA" },
  TH: { name: "Thailand", alpha3: "THA" },
  TG: { name: "Togo", alpha3: "TGO" },
  TO: { name: "Tonga", alpha3: "TON" },
  TT: { name: "Trinidad and Tobago", alpha3: "TTO" },
  TN: { name: "Tunisia", alpha3: "TUN" },
  TR: { name: "Turkey", alpha3: "TUR" },
  TM: { name: "Turkmenistan", alpha3: "TKM" },
  TV: { name: "Tuvalu", alpha3: "TUV" },
  UG: { name: "Uganda", alpha3: "UGA" },
  UA: { name: "Ukraine", alpha3: "UKR" },
  AE: { name: "United Arab Emirates", alpha3: "ARE" },
  GB: {
    name: "United Kingdom",
    alpha3: "GBR",
    eori: true,
    registrationNumber: true
  },
  US: { name: "United States", alpha3: "USA" },
  UY: { name: "Uruguay", alpha3: "URY" },
  UZ: { name: "Uzbekistan", alpha3: "UZB" },
  VU: { name: "Vanuatu", alpha3: "VUT" },
  VA: { name: "Vatican City", alpha3: "VAT" },
  VE: { name: "Venezuela", alpha3: "VEN" },
  VN: { name: "Vietnam", alpha3: "VNM" },
  YE: { name: "Yemen", alpha3: "YEM" },
  ZM: { name: "Zambia", alpha3: "ZMB" },
  ZW: { name: "Zimbabwe", alpha3: "ZWE" }
};

type CountryProfile = {
  eori?: boolean;
  registrationNumber?: boolean;
};

export function getCountryProfile(
  countryCode: string | null | undefined
): CountryProfile | undefined {
  if (!countryCode) return undefined;
  const entry = COUNTRY_MAP[countryCode.toUpperCase()];
  if (!entry || (!entry.eori && !entry.registrationNumber)) return undefined;
  return { eori: entry.eori, registrationNumber: entry.registrationNumber };
}

export function isEoriCountry(countryCode: string | null | undefined): boolean {
  return getCountryProfile(countryCode)?.eori === true;
}

export function isRegistrationNumberCountry(
  countryCode: string | null | undefined
): boolean {
  return getCountryProfile(countryCode)?.registrationNumber === true;
}
