#!/usr/bin/env bash
#
# Carbon — single-VPS Docker Swarm deploy helper.
#
# Wraps the Swarm stack: bootstraps secrets, builds the app images, deploys the
# stack, and runs DB migrations in the correct order. See README.md.
#
# Usage:
#   ./deploy.sh init [--force]    # swarm init + create Docker secrets + .env
#   ./deploy.sh build             # build erp+mes images on this host
#   ./deploy.sh deploy            # docker stack deploy
#   ./deploy.sh up                # build + deploy + wait + migrate (one shot)
#   ./deploy.sh migrate           # (re)apply DB migrations only
#   ./deploy.sh secret <name>     # create/rotate one secret from stdin
#   ./deploy.sh status            # services + tasks
#   ./deploy.sh logs <service>    # follow a service's logs (e.g. erp, caddy)
#   ./deploy.sh down [--volumes]  # remove the stack (--volumes also wipes data)
#
set -euo pipefail

readonly SCRIPT_NAME=$(basename "$0")
readonly HERE=$(cd "$(dirname "$0")" && pwd)
readonly STACK_FILE="$HERE/stack.yml"
readonly ENV_FILE="$HERE/.env"
readonly ENV_EXAMPLE="$HERE/.env.example"

# Secrets generated by `init` (value auto-created) vs. supplied by the operator.
readonly GENERATED_SECRETS="postgres_password session_secret inngest_signing_key inngest_event_key"
readonly TRIO_SECRETS="jwt_secret anon_key service_role_key"
readonly SUPPLIED_SECRETS="resend_api_key smtp_password"

log()   { printf '\033[0;36m[%s]\033[0m %s\n' "$(date '+%H:%M:%S')" "$*"; }
warn()  { printf '\033[0;33m[warn]\033[0m %s\n' "$*" >&2; }
error() { printf '\033[0;31m[error]\033[0m %s\n' "$*" >&2; exit 1; }

require_cmds() {
	local missing=()
	for c in "$@"; do command -v "$c" >/dev/null 2>&1 || missing+=("$c"); done
	[ ${#missing[@]} -eq 0 ] || error "missing required command(s): ${missing[*]}"
}

load_env() {
	[ -f "$ENV_FILE" ] || error ".env not found — run '$SCRIPT_NAME init' first"
	set -a; . "$ENV_FILE"; set +a
	: "${CARBON_REPO:?CARBON_REPO must be set in .env}"
	: "${STACK_NAME:?STACK_NAME must be set in .env}"
	[ -f "$CARBON_REPO/Dockerfile" ] || error "CARBON_REPO=$CARBON_REPO is not a Carbon checkout (no Dockerfile)"
}

swarm_active() { [ "$(docker info --format '{{.Swarm.LocalNodeState}}' 2>/dev/null)" = "active" ]; }
secret_exists() { docker secret inspect "$1" >/dev/null 2>&1; }
create_secret() { printf '%s' "$2" | docker secret create "$1" - >/dev/null && log "secret '$1' created"; }

# ── init ──────────────────────────────────────────────────────────────────────
cmd_init() {
	require_cmds docker node openssl
	local force=0; [ "${1:-}" = "--force" ] && force=1

	swarm_active || { log "Initializing Docker Swarm"; docker swarm init >/dev/null; }

	if [ ! -f "$ENV_FILE" ]; then
		log "Creating .env from .env.example — edit it before deploying"
		cp "$ENV_EXAMPLE" "$ENV_FILE"
	fi

	# Bind-mounted scripts must be executable on the host.
	chmod +x "$HERE/bin/secrets-entrypoint.sh" "$HERE/postgres/"*.sh

	log "Creating Docker secrets (skipping any that already exist)"
	local s
	for s in $GENERATED_SECRETS; do
		if secret_exists "$s" && [ "$force" -ne 1 ]; then log "secret '$s' exists — skip"; continue; fi
		secret_exists "$s" && docker secret rm "$s" >/dev/null
		case "$s" in
			postgres_password) create_secret "$s" "$(openssl rand -hex 24)" ;;
			session_secret)    create_secret "$s" "$(openssl rand -hex 32)" ;;
			# Inngest self-host rejects the signkey- prefix — plain hex only.
			inngest_signing_key) create_secret "$s" "$(openssl rand -hex 32)" ;;
			inngest_event_key)   create_secret "$s" "$(openssl rand -hex 16)" ;;
		esac
	done

	# Supabase key trio — must be minted together (anon/service signed by jwt_secret).
	if secret_exists jwt_secret && [ "$force" -ne 1 ]; then
		log "secret 'jwt_secret' exists — skipping Supabase trio"
	else
		log "Generating Supabase key trio"
		local trio jwt anon svc
		trio=$(node "$HERE/scripts/gen-supabase-keys.mjs")
		jwt=$(printf '%s\n' "$trio"  | sed -n 's/^SUPABASE_JWT_SECRET=//p')
		anon=$(printf '%s\n' "$trio" | sed -n 's/^SUPABASE_ANON_KEY=//p')
		svc=$(printf '%s\n' "$trio"  | sed -n 's/^SUPABASE_SERVICE_ROLE_KEY=//p')
		for s in jwt_secret anon_key service_role_key; do secret_exists "$s" && docker secret rm "$s" >/dev/null; done
		create_secret jwt_secret "$jwt"
		create_secret anon_key "$anon"
		create_secret service_role_key "$svc"
	fi

	# Operator-supplied secrets — placeholders so the stack deploys; replace later.
	# ERP crashes on boot with an empty RESEND_API_KEY, so seed a non-empty value.
	for s in $SUPPLIED_SECRETS; do
		secret_exists "$s" && continue
		case "$s" in
			resend_api_key) create_secret "$s" "re_placeholder_change_me" ;;
			smtp_password)  create_secret "$s" "change_me" ;;
		esac
	done

	log "Secrets ready."
	warn "Next:"
	warn "  1. Edit $ENV_FILE — set CARBON_REPO, the *_HOST/*_URL, ACME_EMAIL, SMTP."
	warn "  2. Set real secrets:  $SCRIPT_NAME secret resend_api_key   (then smtp_password)"
	warn "  3. $SCRIPT_NAME up"
}

# ── build ──────────────────────────────────────────────────────────────────────
cmd_build() {
	require_cmds docker; load_env
	if [ -n "${CARBON_REGISTRY:-}" ]; then
		log "CARBON_REGISTRY set — skipping local build (images pulled from registry on deploy)"
		return 0
	fi
	log "Building erp image ($CARBON_IMAGE_ERP) — needs ~8 GB RAM (NODE_OPTIONS)"
	docker build --build-arg APP=erp -t "$CARBON_IMAGE_ERP" "$CARBON_REPO"
	log "Building mes image ($CARBON_IMAGE_MES)"
	docker build --build-arg APP=mes -t "$CARBON_IMAGE_MES" "$CARBON_REPO"
}

# ── deploy ─────────────────────────────────────────────────────────────────────
cmd_deploy() {
	require_cmds docker; load_env
	swarm_active || error "swarm not active — run '$SCRIPT_NAME init'"
	log "Deploying stack '$STACK_NAME'"
	# --resolve-image never: use the locally built tags as-is for the no-registry path.
	local resolve=never; [ -n "${CARBON_REGISTRY:-}" ] && resolve=always
	docker stack deploy --detach=true --resolve-image "$resolve" -c "$STACK_FILE" "$STACK_NAME"
}

# Wait until a service has a healthy (or, if no healthcheck, running) task.
wait_healthy() {
	local svc="$1" timeout="${2:-180}" name="${STACK_NAME}_$1" waited=0
	log "Waiting for $name to be healthy (timeout ${timeout}s)"
	while [ "$waited" -lt "$timeout" ]; do
		if docker ps --filter "name=$name" --filter health=healthy --format '{{.Names}}' | grep -q .; then
			log "$name healthy"; return 0
		fi
		sleep 5; waited=$((waited + 5))
	done
	error "$name not healthy after ${timeout}s — check '$SCRIPT_NAME logs $svc'"
}

# ── migrate (ephemeral run-once job on the stack network) ───────────────────────
cmd_migrate() {
	require_cmds docker; load_env
	wait_healthy postgres 180
	wait_healthy storage 180
	local job="${STACK_NAME}_migrate"
	docker service rm "$job" >/dev/null 2>&1 || true
	log "Running migrations (supabase migration up)"
	docker service create \
		--name "$job" \
		--mode replicated-job \
		--detach=false \
		--network "${STACK_NAME}_internal" \
		--secret postgres_password \
		--restart-condition on-failure \
		--restart-max-attempts 30 \
		--env PGSSLMODE=disable \
		--workdir /repo/packages/database \
		"$CARBON_IMAGE_ERP" \
		sh -c 'pnpm exec supabase migration up --include-all \
			--db-url "postgresql://supabase_admin:$(cat /run/secrets/postgres_password)@postgres:5432/postgres"'
	docker service rm "$job" >/dev/null 2>&1 || true
	log "Migrations applied"
}

# ── up (build + deploy + migrate + roll apps) ───────────────────────────────────
cmd_up() {
	cmd_build
	cmd_deploy
	cmd_migrate
	load_env
	log "Rolling apps now that the schema exists"
	docker service update --force --detach=true "${STACK_NAME}_erp" >/dev/null
	docker service update --force --detach=true "${STACK_NAME}_mes" >/dev/null
	log "Stack up. Check: $SCRIPT_NAME status"
}

# ── secret (create or rotate one secret from stdin) ─────────────────────────────
cmd_secret() {
	require_cmds docker
	local name="${1:?usage: $SCRIPT_NAME secret <name> (value read from stdin)}"
	local val; val=$(cat)
	[ -n "$val" ] || error "empty value on stdin"
	if secret_exists "$name"; then
		warn "secret '$name' exists. Rotating requires services to re-read it:"
		warn "  $SCRIPT_NAME down && $SCRIPT_NAME secret $name && $SCRIPT_NAME up"
		docker secret rm "$name" >/dev/null 2>&1 || error "secret '$name' is in use — bring the stack down first"
	fi
	create_secret "$name" "$val"
}

cmd_status() {
	load_env
	docker stack services "$STACK_NAME"
	echo
	docker stack ps "$STACK_NAME" --no-trunc --filter desired-state=running
}

cmd_logs() {
	load_env
	local svc="${1:?usage: $SCRIPT_NAME logs <service>}"
	docker service logs -f --tail 200 "${STACK_NAME}_${svc}"
}

cmd_down() {
	require_cmds docker; load_env
	log "Removing stack '$STACK_NAME'"
	docker stack rm "$STACK_NAME"
	if [ "${1:-}" = "--volumes" ]; then
		warn "Waiting for tasks to stop, then deleting volumes (DATA LOSS)"
		sleep 10
		docker volume ls -q --filter "name=${STACK_NAME}_" | xargs -r docker volume rm
	fi
}

usage() { sed -n '10,28p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

main() {
	local sub="${1:-}"; [ $# -gt 0 ] && shift || true
	case "$sub" in
		init)    cmd_init "$@" ;;
		build)   cmd_build "$@" ;;
		deploy)  cmd_deploy "$@" ;;
		up)      cmd_up "$@" ;;
		migrate) cmd_migrate "$@" ;;
		secret)  cmd_secret "$@" ;;
		status)  cmd_status "$@" ;;
		logs)    cmd_logs "$@" ;;
		down)    cmd_down "$@" ;;
		-h|--help|help|"") usage 0 ;;
		*) error "unknown command: $sub (try '$SCRIPT_NAME --help')" ;;
	esac
}

main "$@"
