// SPDX-License-Identifier: AGPL-3.0-only
// Carbon (github.com/crbnos/carbon). Modified or adapted versions of this file,
// including ports, remain AGPLv3; serving them over a network requires releasing their source.

// The journal of a legacy sales invoice: the lines `post-sales-invoice`
// writes today, from the stored invoice, with today's account defaults
// (.ai/specs/2026-10-08-accounting-cutover.md section 5a).
//
// Mirrors post-sales-invoice/index.ts:
// - receivables, revenue, shipping and tax through `buildSalesPostingLines`,
//   with the same context (`sales-invoice:<salesOrderLineId>`, the customer
//   reference, the intercompany partner) and metadata (~1157-1295);
// - the COGS pair of a direct line (no sales order, not Make to Order,
//   inventory-tracked) at the cost its cost row stored (~1368-1415,
//   ~1861-1920). A line with no cost row gets no pair here: the movement
//   families of the enable write that cost row and its journal;
// - the dimensions of every line (~1960-2045).
// A contract, rental or fixed-asset line books plain revenue on the sales
// account. A line with Deferral schedule rows dated on or after the cutover
// credits their sum to the rows' deferred revenue account, as the posting
// deferred it; a recognition run (or the enable's rebuild of a posted run)
// moves those rows to revenue. Rows dated before the cutover were settled
// in the opening balance with no journal, so their share books to sales.
// Not rebuilt: the intercompany transaction record, schedule rows, contract
// movements and asset disposals. They are not journal lines, and the
// posting already wrote what it writes for every company.

import { type Database, journalReference } from "@carbon/database";
import type { KyselyTx } from "@carbon/database/client";
import {
  type OptionalDefaultRole,
  resolveDefaultAccount
} from "@carbon/database/journal-posting-status";
import {
  allocateSalesHeaderShipping,
  buildSalesPostingLines,
  credit,
  debit,
  round,
  type SalesPostingAccount,
  type SalesPostingMetadata,
  type SalesRevenueLeg
} from "@carbon/utils";
import { sql } from "kysely";
import { nanoid } from "nanoid";
import { resolveInventoryAccount } from "../../lib/get-posting-group";
import { legacySalesInvoices } from "./detect";
import { type LegacyJournal, type LegacyJournalLine, readByIds } from "./write";

type AccountDefaults = Database["public"]["Tables"]["accountDefault"]["Row"];

// The optional defaults this journal reads, with the class each must have,
// as post-sales-invoice's STAND_IN_CLASS.
const STAND_IN_CLASS = {
  deferredRevenueAccount: "Liability",
  intercompanyReceivablesAccount: "Asset",
  salesShippingRevenueAccount: "Revenue"
} as const satisfies Partial<Record<OptionalDefaultRole, string>>;
type StandInRole = keyof typeof STAND_IN_CLASS;
// Never an account id: account ids are generated by id('…').
const STAND_IN_PREFIX = "stand-in:";

const ITEM_LINE_TYPES = new Set([
  "Part",
  "Service",
  "Consumable",
  "Fixture",
  "Material",
  "Tool"
]);

export async function buildLegacySalesInvoiceJournals(
  trx: KyselyTx,
  {
    companyId,
    companyGroupId,
    cutoverDate,
    defaults
  }: {
    companyId: string;
    companyGroupId: string;
    cutoverDate: string;
    defaults: AccountDefaults;
  }
): Promise<LegacyJournal[]> {
  const invoices = await legacySalesInvoices(trx, { companyId, cutoverDate });
  if (invoices.length === 0) return [];
  const invoiceIds = invoices.map((invoice) => invoice.id);

  const lines = await readByIds(invoiceIds, (ids) =>
    trx
      .selectFrom("salesInvoiceLine")
      .selectAll()
      .where("companyId", "=", companyId)
      .where("invoiceId", "in", ids)
      .orderBy("invoiceId")
      .orderBy("createdAt")
      .orderBy("id")
      .execute()
  );
  const lineIds = lines.map((line) => line.id);
  const itemIds = lines.map((line) => line.itemId);

  const shipments = await readByIds(invoiceIds, (ids) =>
    trx
      .selectFrom("salesInvoiceShipment")
      .select(["id", "shippingCost"])
      .where("companyId", "=", companyId)
      .where("id", "in", ids)
      .execute()
  );
  const customers = await readByIds(
    invoices.map((invoice) => invoice.customerId),
    (ids) =>
      trx
        .selectFrom("customer")
        .select(["id", "customerTypeId", "intercompanyCompanyId"])
        .where("companyId", "=", companyId)
        .where("id", "in", ids)
        .execute()
  );
  const items = await readByIds(itemIds, (ids) =>
    trx
      .selectFrom("item")
      .select(["id", "itemTrackingType", "replenishmentSystem"])
      .where("companyId", "=", companyId)
      .where("id", "in", ids)
      .execute()
  );
  const itemCosts = await readByIds(itemIds, (ids) =>
    trx
      .selectFrom("itemCost")
      .select(["itemId", "itemPostingGroupId"])
      .where("companyId", "=", companyId)
      .where("itemId", "in", ids)
      .execute()
  );
  const salesOrderLines = await readByIds(
    lines.map((line) => line.salesOrderLineId),
    (ids) =>
      trx
        .selectFrom("salesOrderLine")
        .select(["id", "locationId"])
        .where("companyId", "=", companyId)
        .where("id", "in", ids)
        .execute()
  );
  const assets = await readByIds(
    lines.map((line) => line.assetId),
    (ids) =>
      trx
        .selectFrom("fixedAsset")
        .select(["id", "locationId", "fixedAssetClassId"])
        .where("companyId", "=", companyId)
        .where("id", "in", ids)
        .execute()
  );
  const agreementLines = await readByIds(
    lines.map((line) => line.rentalAgreementLineId),
    (ids) =>
      trx
        .selectFrom("rentalAgreementLine")
        .select(["id", "itemId"])
        .where("companyId", "=", companyId)
        .where("id", "in", ids)
        .execute()
  );
  // What the posting deferred and a run has still to recognize: each line's
  // Deferral rows dated on or after the cutover, per deferred revenue account.
  const deferrals = await readByIds(lineIds, (ids) =>
    trx
      .selectFrom("revenueRecognitionSchedule")
      .select([
        "salesInvoiceLineId",
        "debitAccountId",
        sql<number>`sum("amount")`.as("amount")
      ])
      .where("companyId", "=", companyId)
      .where("salesInvoiceLineId", "in", ids)
      .where("type", "=", "Deferral")
      .where("scheduledDate", ">=", cutoverDate)
      .groupBy(["salesInvoiceLineId", "debitAccountId"])
      .orderBy("salesInvoiceLineId")
      .orderBy("debitAccountId")
      .execute()
  );
  // The cost a direct line's shipment relieved, where the posting stored it.
  const costRows = await readByIds(invoiceIds, (ids) =>
    trx
      .selectFrom("costLedger")
      .select(["id", "documentId", "itemId", "quantity", "cost"])
      .where("companyId", "=", companyId)
      .where("documentType", "=", "Sales Shipment")
      .where("documentId", "in", ids)
      .where("adjustment", "=", false)
      .where("quantity", "<", 0)
      .orderBy("entryNumber")
      .execute()
  );

  // Accounts, with the stand-in rule of a posting before the cutover.
  const standInRoles = new Map<string, StandInRole>();
  const defaultId = (role: StandInRole): string => {
    // Inside the enable a posting is still before the cutover.
    const resolved = resolveDefaultAccount(defaults, role, "Provisional");
    if (!resolved.accountDefaultRole) return resolved.accountId;
    const placeholder = `${STAND_IN_PREFIX}${role}`;
    standInRoles.set(placeholder, role);
    return placeholder;
  };
  const deferredAccountId = (debitAccountId: string) =>
    debitAccountId === defaults.retainedEarningsAccount
      ? defaultId("deferredRevenueAccount")
      : debitAccountId;
  const anyIntercompany = customers.some((row) => row.intercompanyCompanyId);
  const receivablesIds = {
    standard: defaults.receivablesAccount,
    intercompany: anyIntercompany
      ? defaultId("intercompanyReceivablesAccount")
      : defaults.receivablesAccount
  };
  const shippingAccountId = defaultId("salesShippingRevenueAccount");
  const accountIds = new Set<string>([
    receivablesIds.standard,
    receivablesIds.intercompany,
    defaults.salesAccount,
    shippingAccountId,
    defaults.salesTaxPayableAccount,
    ...deferrals.map((row) => deferredAccountId(row.debitAccountId))
  ]);
  const accountRows = await readByIds(
    [...accountIds].filter((id) => !standInRoles.has(id)),
    (ids) =>
      trx
        .selectFrom("account")
        .select(["id", "class", "active", "isGroup", "companyGroupId"])
        .where("companyGroupId", "=", companyGroupId)
        .where("id", "in", ids)
        .execute()
  );
  const accountsById = new Map<string, SalesPostingAccount>(
    accountRows.map((row) => [
      row.id,
      { ...row, companyGroupId: row.companyGroupId ?? "" }
    ])
  );
  for (const [placeholder, role] of standInRoles) {
    accountsById.set(placeholder, {
      id: placeholder,
      class: STAND_IN_CLASS[role],
      active: true,
      isGroup: false,
      companyGroupId
    });
  }
  const account = (id: string) => accountsById.get(id);

  const linesByInvoice = groupBy(lines, (line) => line.invoiceId);
  const shippingByInvoice = new Map(
    shipments.map((row) => [row.id, Number(row.shippingCost ?? 0)])
  );
  const customerById = new Map(customers.map((row) => [row.id, row]));
  const itemById = new Map(items.map((row) => [row.id, row]));
  const postingGroupByItem = new Map(
    itemCosts.map((row) => [row.itemId, row.itemPostingGroupId])
  );
  const salesOrderLineById = new Map(
    salesOrderLines.map((row) => [row.id, row])
  );
  const assetById = new Map(assets.map((row) => [row.id, row]));
  const agreementLineById = new Map(agreementLines.map((row) => [row.id, row]));
  const deferralsByLine = groupBy(
    deferrals,
    (row) => row.salesInvoiceLineId ?? ""
  );
  const costRowsByInvoice = groupBy(costRows, (row) => row.documentId ?? "");

  return invoices.map((invoice) => {
    const customer = invoice.customerId
      ? customerById.get(invoice.customerId)
      : undefined;
    const intercompanyPartnerId = customer?.intercompanyCompanyId ?? null;
    const chargeAccounts = {
      receivables: account(
        intercompanyPartnerId
          ? receivablesIds.intercompany
          : receivablesIds.standard
      ),
      sales: account(defaults.salesAccount),
      shipping: account(shippingAccountId),
      tax: account(defaults.salesTaxPayableAccount)
    };
    const invoiceLines = linesByInvoice.get(invoice.id) ?? [];
    const headerShipping = allocateSalesHeaderShipping(
      invoiceLines,
      shippingByInvoice.get(invoice.id) ?? 0
    );
    const unusedCostRows = [...(costRowsByInvoice.get(invoice.id) ?? [])];
    const journalLines: LegacyJournalLine[] = [];
    const push = (
      line: Omit<LegacyJournalLine, "dimensions">,
      meta: SalesPostingMetadata
    ) => {
      const role = line.accountId ? standInRoles.get(line.accountId) : null;
      journalLines.push({
        ...line,
        ...(role
          ? {
              accountId: defaults.retainedEarningsAccount,
              accountDefaultRole: role
            }
          : {}),
        dimensions: {
          CustomerType: meta.customerTypeId,
          ItemPostingGroup: meta.itemPostingGroupId,
          Location: meta.locationId,
          CostCenter: meta.costCenterId,
          FixedAssetClass: meta.fixedAssetClassId,
          Item: meta.itemId,
          Project: meta.projectId ?? null,
          Customer: invoice.customerId
        }
      });
    };

    for (const invoiceLine of invoiceLines) {
      if (invoiceLine.invoiceLineType === "Comment") continue;
      const isAsset = invoiceLine.invoiceLineType === "Fixed Asset";
      const isRental = invoiceLine.invoiceLineType === "Rental";
      const asset = invoiceLine.assetId
        ? assetById.get(invoiceLine.assetId)
        : undefined;
      const agreementLine = invoiceLine.rentalAgreementLineId
        ? agreementLineById.get(invoiceLine.rentalAgreementLineId)
        : undefined;
      const metadata: SalesPostingMetadata = {
        customerTypeId: customer?.customerTypeId ?? null,
        itemPostingGroupId:
          isAsset || isRental || !invoiceLine.itemId
            ? null
            : (postingGroupByItem.get(invoiceLine.itemId) ?? null),
        itemId: isAsset
          ? null
          : isRental
            ? (agreementLine?.itemId ?? null)
            : (invoiceLine.itemId ?? null),
        locationId: isAsset
          ? (invoiceLine.locationId ??
            (invoiceLine.salesOrderLineId
              ? salesOrderLineById.get(invoiceLine.salesOrderLineId)?.locationId
              : null) ??
            asset?.locationId ??
            null)
          : (invoiceLine.locationId ?? null),
        costCenterId: null,
        fixedAssetClassId: isAsset ? (asset?.fixedAssetClassId ?? null) : null,
        projectId: invoiceLine.projectId ?? null
      };
      const deferred = deferralsByLine.get(invoiceLine.id) ?? [];
      const revenueLegs: SalesRevenueLeg[] | undefined =
        deferred.length > 0
          ? [
              ...deferred.map((row) => ({
                account: account(deferredAccountId(row.debitAccountId)),
                accountClass: "Liability" as const,
                description: "Deferred Revenue",
                amount: Number(row.amount)
              })),
              {
                account: chargeAccounts.sales,
                accountClass: "Revenue" as const,
                description: "Sales Account"
              }
            ]
          : undefined;
      const charges = buildSalesPostingLines({
        line: {
          ...invoiceLine,
          // A contract, rental or fixed-asset line books plain revenue.
          invoiceLineType:
            isAsset || isRental ? "Part" : invoiceLine.invoiceLineType,
          allocatedHeaderShipping: headerShipping.get(invoiceLine.id) ?? 0
        },
        context: {
          companyId,
          companyGroupId,
          documentId: invoice.id,
          externalDocumentId: invoice.customerReference,
          documentLineReference: invoiceLine.salesOrderLineId
            ? journalReference.to.salesInvoice(invoiceLine.salesOrderLineId)
            : null,
          journalLineReference: nanoid(),
          intercompanyPartnerId
        },
        accounts: chargeAccounts,
        revenueLegs,
        metadata
      });
      charges.lines.forEach((line, index) => {
        push(line, charges.metadata[index] ?? metadata);
      });

      // The COGS pair of a direct line, at the cost its cost row stored.
      const item = invoiceLine.itemId
        ? itemById.get(invoiceLine.itemId)
        : undefined;
      if (
        ITEM_LINE_TYPES.has(invoiceLine.invoiceLineType) &&
        invoiceLine.itemId &&
        invoiceLine.salesOrderLineId === null &&
        invoiceLine.methodType !== "Make to Order" &&
        (item?.itemTrackingType ?? "Inventory") === "Inventory"
      ) {
        const quantity = round(Number(invoiceLine.quantity));
        const sameItem = unusedCostRows.filter(
          (row) => row.itemId === invoiceLine.itemId
        );
        const costRow =
          sameItem.find((row) => round(-Number(row.quantity)) === quantity) ??
          sameItem[0];
        if (costRow) {
          unusedCostRows.splice(unusedCostRows.indexOf(costRow), 1);
          const cost = -Number(costRow.cost);
          const inventoryAccount = resolveInventoryAccount(
            item?.replenishmentSystem ?? null,
            defaults
          );
          const keys = {
            quantity,
            documentType: "Invoice" as const,
            documentId: invoice.id,
            externalDocumentId: invoice.customerReference,
            journalLineReference: nanoid()
          };
          const cogsMetadata = { ...metadata, projectId: null };
          push(
            {
              accountId: defaults.costOfGoodsSoldAccount,
              description: "Cost of Goods Sold",
              amount: round(debit("expense", cost)),
              ...keys
            },
            cogsMetadata
          );
          push(
            {
              accountId: inventoryAccount.account,
              description: inventoryAccount.description,
              amount: round(credit("asset", cost)),
              ...keys
            },
            cogsMetadata
          );
        }
      }
    }

    return {
      description: `Sales Invoice ${invoice.invoiceId}`,
      postingDate: String(invoice.postingDate),
      sourceType: "Sales Invoice" as const,
      lines: journalLines
    };
  });
}

function groupBy<T>(rows: T[], key: (row: T) => string): Map<string, T[]> {
  const map = new Map<string, T[]>();
  for (const row of rows) {
    const k = key(row);
    const list = map.get(k);
    if (list) list.push(row);
    else map.set(k, [row]);
  }
  return map;
}
