#pragma once
#include <cstdint>
#include "rust/cxx.h"

namespace carbon_occt {
struct Tree;  // generated by cxx from the shared struct

Tree read_step(rust::Str path, double linear_deflection, double angular_deflection);
}  // namespace carbon_occt
