#pragma once
#include <cstdint>
#include "rust/cxx.h"

namespace carbon_occt {
struct Tree;  // generated by cxx from the shared struct

Tree read_step(rust::Str path, double linear_deflection, double angular_deflection);

Tree read_iges(rust::Str path, double linear_deflection, double angular_deflection);

Tree read_brep(rust::Str path, double linear_deflection, double angular_deflection);

bool step_to_xbf(rust::Str step_path, rust::Str xbf_path);

Tree read_xbf(rust::Str path, double linear_deflection, double angular_deflection);

bool write_test_step(rust::Str path, uint32_t boxes);

bool write_test_cylinder(rust::Str path, double radius, double height);

bool write_test_plate_with_holes(rust::Str path, double size, double thickness,
                                 double hole_radius, uint32_t holes);
}  // namespace carbon_occt
