// GENERATED FILE — do not edit. Run `pnpm run generate:workflow-catalog`.

import type { MessageDescriptor } from "@lingui/core";
import { msg } from "@lingui/core/macro";

export const WORKFLOW_EVENT_LABELS: Record<string, MessageDescriptor> = {
  "customer.accountManagerId.changed": msg`A customer's account manager changes`,
  "customer.assignee.changed": msg`A customer's assignee changes`,
  "customer.created": msg`A customer is created`,
  "customer.currencyCode.changed": msg`A customer's currency changes`,
  "customer.customerStatusId.changed": msg`A customer's status changes`,
  "customer.customerTypeId.changed": msg`A customer's type changes`,
  "customer.deleted": msg`A customer is deleted`,
  "customer.name.changed": msg`A customer's name changes`,
  "customer.salesContactId.changed": msg`A customer's sales contact changes`,
  "inventory.receiptPosted": msg`A receipt is posted`,
  "inventory.shipmentPosted": msg`A shipment is posted`,
  "invoicing.purchaseInvoicePosted": msg`A purchase invoice is posted`,
  "invoicing.salesInvoicePosted": msg`A sales invoice is posted`,
  "item.active.changed": msg`An item's active changes`,
  "item.assignee.changed": msg`An item's assignee changes`,
  "item.created": msg`An item is created`,
  "item.defaultMethodType.changed": msg`An item's default method type changes`,
  "item.deleted": msg`An item is deleted`,
  "item.itemTrackingType.changed": msg`An item's tracking type changes`,
  "item.name.changed": msg`An item's name changes`,
  "item.replenishmentSystem.changed": msg`An item's replenishment system changes`,
  "item.revisionStatus.changed": msg`An item's revision status changes`,
  "item.unitOfMeasureCode.changed": msg`An item's unit of measure changes`,
  "job.assignee.changed": msg`A job's assignee changes`,
  "job.created": msg`A job is created`,
  "job.deadlineType.changed": msg`A job's deadline type changes`,
  "job.deleted": msg`A job is deleted`,
  "job.dueDate.changed": msg`A job's due date changes`,
  "job.priority.changed": msg`A job's priority changes`,
  "job.quantity.changed": msg`A job's quantity changes`,
  "job.scrapQuantity.changed": msg`A job's scrap quantity changes`,
  "job.startDate.changed": msg`A job's start date changes`,
  "job.status.changed": msg`A job's status changes`,
  "nonConformance.assignee.changed": msg`An issue's assignee changes`,
  "nonConformance.closeDate.changed": msg`An issue's close date changes`,
  "nonConformance.created": msg`An issue is created`,
  "nonConformance.deleted": msg`An issue is deleted`,
  "nonConformance.dueDate.changed": msg`An issue's due date changes`,
  "nonConformance.locationId.changed": msg`An issue's location changes`,
  "nonConformance.nonConformanceTypeId.changed": msg`An issue's type changes`,
  "nonConformance.priority.changed": msg`An issue's priority changes`,
  "nonConformance.quantity.changed": msg`An issue's quantity changes`,
  "nonConformance.source.changed": msg`An issue's source changes`,
  "nonConformance.status.changed": msg`An issue's status changes`,
  "production.jobHeld": msg`A job is put on hold`,
  "production.jobOperationCompleted": msg`A job operation is completed`,
  "production.jobReleased": msg`A job is released`,
  "purchaseOrder.assignee.changed": msg`A purchase order's assignee changes`,
  "purchaseOrder.created": msg`A purchase order is created`,
  "purchaseOrder.deleted": msg`A purchase order is deleted`,
  "purchaseOrder.orderDate.changed": msg`A purchase order's order date changes`,
  "purchaseOrder.purchaseOrderType.changed": msg`A purchase order's type changes`,
  "purchaseOrder.status.changed": msg`A purchase order's status changes`,
  "purchaseOrder.supplierId.changed": msg`A purchase order's supplier changes`,
  "purchaseOrder.supplierLocationId.changed": msg`A purchase order's supplier location changes`,
  "purchaseOrder.supplierReference.changed": msg`A purchase order's supplier reference changes`,
  "purchaseOrder.tags.changed": msg`A purchase order's tags changes`,
  "quote.assignee.changed": msg`A quote's assignee changes`,
  "quote.completedDate.changed": msg`A quote's completed date changes`,
  "quote.created": msg`A quote is created`,
  "quote.customerId.changed": msg`A quote's customer changes`,
  "quote.deleted": msg`A quote is deleted`,
  "quote.dueDate.changed": msg`A quote's due date changes`,
  "quote.estimatorId.changed": msg`A quote's estimator changes`,
  "quote.expirationDate.changed": msg`A quote's expiration date changes`,
  "quote.salesPersonId.changed": msg`A quote's salesperson changes`,
  "quote.status.changed": msg`A quote's status changes`,
  "receipt.assignee.changed": msg`A receipt's assignee changes`,
  "receipt.created": msg`A receipt is created`,
  "receipt.deleted": msg`A receipt is deleted`,
  "receipt.invoiced.changed": msg`A receipt's invoiced changes`,
  "receipt.locationId.changed": msg`A receipt's location changes`,
  "receipt.postingDate.changed": msg`A receipt's posting date changes`,
  "receipt.sourceDocument.changed": msg`A receipt's source document changes`,
  "receipt.status.changed": msg`A receipt's status changes`,
  "receipt.supplierId.changed": msg`A receipt's supplier changes`,
  "sales.quoteAccepted": msg`A quote is accepted`,
  "sales.quoteSent": msg`A quote is sent`,
  "salesOrder.assignee.changed": msg`A sales order's assignee changes`,
  "salesOrder.completedDate.changed": msg`A sales order's completed date changes`,
  "salesOrder.created": msg`A sales order is created`,
  "salesOrder.customerId.changed": msg`A sales order's customer changes`,
  "salesOrder.customerReference.changed": msg`A sales order's customer reference changes`,
  "salesOrder.deleted": msg`A sales order is deleted`,
  "salesOrder.locationId.changed": msg`A sales order's location changes`,
  "salesOrder.orderDate.changed": msg`A sales order's order date changes`,
  "salesOrder.salesPersonId.changed": msg`A sales order's salesperson changes`,
  "salesOrder.status.changed": msg`A sales order's status changes`,
  "shipment.assignee.changed": msg`A shipment's assignee changes`,
  "shipment.created": msg`A shipment is created`,
  "shipment.customerId.changed": msg`A shipment's customer changes`,
  "shipment.deleted": msg`A shipment is deleted`,
  "shipment.locationId.changed": msg`A shipment's location changes`,
  "shipment.postingDate.changed": msg`A shipment's posting date changes`,
  "shipment.shippingMethodId.changed": msg`A shipment's shipping method changes`,
  "shipment.status.changed": msg`A shipment's status changes`,
  "shipment.trackingNumber.changed": msg`A shipment's tracking number changes`,
  "supplier.accountManagerId.changed": msg`A supplier's account manager changes`,
  "supplier.assignee.changed": msg`A supplier's assignee changes`,
  "supplier.created": msg`A supplier is created`,
  "supplier.currencyCode.changed": msg`A supplier's currency changes`,
  "supplier.deleted": msg`A supplier is deleted`,
  "supplier.name.changed": msg`A supplier's name changes`,
  "supplier.supplierStatus.changed": msg`A supplier's status changes`,
  "supplier.supplierTypeId.changed": msg`A supplier's type changes`,
  "supplier.taxPercent.changed": msg`A supplier's tax percent changes`
};
