// SPDX-License-Identifier: AGPL-3.0-only
// Carbon (github.com/crbnos/carbon). Modified or adapted versions of this file,
// including ports, remain AGPLv3; serving them over a network requires releasing their source.

// Types for the generated Carbon API operation manifest. The DATA is generated by
// `scripts/generate-mcp.ts` into the erp app's gitignored
// `routes/api+/mcp+/lib/tool-metadata.json` (its committed record is the sibling
// `tool-manifest.digest.json`); these types are the contract consumers read against.
// Keep them in sync with the generator's output shape.

export type Classification = "READ" | "WRITE" | "DESTRUCTIVE";

/** Audit/identity fields the dispatcher stamps into a service payload. */
export type AuthField =
  | "companyId"
  | "companyGroupId"
  | "createdBy"
  | "updatedBy"
  | "userId";

export type PermissionAction = "view" | "create" | "update" | "delete";

/**
 * The permission an API-key caller must hold to invoke the operation.
 * `module` is `null` for operations that gate only on a valid key of the company
 * (e.g. `account`, `shared`) rather than a specific permission module.
 */
export interface ToolPermission {
  module: string | null;
  actions: PermissionAction[];
}

/** One operation in the manifest — the successor of a `tool-metadata.json` entry. */
export interface ManifestEntry {
  name: string;
  module: string;
  classification: Classification;
  description: string;
  paramCount: number;
  serviceParams: string[];
  injectAuth: AuthField[];
  permission: ToolPermission;
  /** Whether the service itself applies limit/offset (`setGenericQueryFilters`
   *  or a direct `.range(`). A list operation with `paginates: false` is a
   *  fetchAll read — pagination args are inert in the service, and the MCP
   *  layer pages the response at its own boundary instead. */
  paginates: boolean;
  /** Present when the service picks insert-vs-update by testing for an audit
   *  field on the payload (`"createdBy" in payload`), so the dispatcher has to
   *  stamp exactly one of them. `keys` are the payload fields that identify the
   *  record; a call missing any of them is a create. With no `lookups`, a call
   *  carrying them all is an update. With `lookups`, it is an update only when
   *  one of them finds a row in the caller's company — `match` maps a column of
   *  `table` to the payload field it is compared with. */
  upsert?: {
    keys: string[];
    lookups?: Array<{ table: string; match: Record<string, string> }>;
  };
  /** The JSON Schema for the operation's input. */
  schema: Record<string, unknown>;
  /** The JSON Schema for the operation's RESPONSE `data`, reflected from the
   *  service function's TypeScript return type — absent when nothing useful could
   *  be derived (an `any`, a void, or an opaque shape). Describes the payload the
   *  dispatcher puts in `data`, not the `{ data, count }` envelope around it. */
  responseSchema?: Record<string, unknown>;
}
