// Types for the generated Carbon API operation manifest. The DATA is generated by
// `scripts/generate-mcp.ts` into the erp app's gitignored
// `routes/api+/mcp+/lib/tool-metadata.json` (its committed record is the sibling
// `tool-manifest.digest.json`); these types are the contract consumers read against.
// Keep them in sync with the generator's output shape.

export type Classification = "READ" | "WRITE" | "DESTRUCTIVE";

/** Audit/identity fields the dispatcher stamps into a service payload. */
export type AuthField =
  | "companyId"
  | "companyGroupId"
  | "createdBy"
  | "updatedBy"
  | "userId";

export type PermissionAction = "view" | "create" | "update" | "delete";

/**
 * What a service function's declared return type is, as the dispatcher reads it
 * (`scripts/lib/result-shape.ts` classifies; `normalize-result.server.ts` acts):
 * - `envelope`: `{ data, error?, count? … }` — the error is thrown, `data` returned.
 * - `envelope-array`: an array of envelopes (`Promise.all` over writes) — any
 *   element error is thrown, otherwise each element's `data` is returned.
 * - `void`: nothing is returned.
 * - `plain`: any other value, returned as-is; it cannot carry a failure.
 * - `unknown`: `any`/`unknown`; the dispatcher falls back to unwrapping a
 *   runtime `data` key.
 */
export type ResultShape =
  | "envelope"
  | "envelope-array"
  | "void"
  | "plain"
  | "unknown";

/**
 * The permission an API-key caller must hold to invoke the operation.
 * `module` is `null` for operations that gate only on a valid key of the company
 * (e.g. `account`, `shared`) rather than a specific permission module.
 */
export interface ToolPermission {
  module: string | null;
  actions: PermissionAction[];
}

/** One operation in the manifest — the successor of a `tool-metadata.json` entry. */
export interface ManifestEntry {
  name: string;
  module: string;
  classification: Classification;
  description: string;
  paramCount: number;
  serviceParams: string[];
  injectAuth: AuthField[];
  permission: ToolPermission;
  /** Whether the service itself applies limit/offset (`setGenericQueryFilters`
   *  or a direct `.range(`). A list operation with `paginates: false` is a
   *  fetchAll read — pagination args are inert in the service, and the MCP
   *  layer pages the response at its own boundary instead. */
  paginates: boolean;
  /** The JSON Schema for the operation's input. When the service branches on
   *  `"createdBy" in payload`, a required `_operation: "create" | "update"`
   *  property is present here — that property IS the marker (there is no parallel
   *  flag), matching how the dispatcher decides today. */
  schema: Record<string, unknown>;
  /** The JSON Schema for the operation's RESPONSE `data`, reflected from the
   *  service function's TypeScript return type — absent when nothing useful could
   *  be derived (an `any`, a void, or an opaque shape). Describes the payload the
   *  dispatcher puts in `data`, not the `{ data, count }` envelope around it. */
  responseSchema?: Record<string, unknown>;
  /** How the dispatcher turns the service's return value into data or an error.
   *  Absent only in a manifest generated before result shapes were recorded. */
  resultShape?: ResultShape;
  /** Envelope keys beside `data`/`error` (e.g. `cta`, `hasMore`) that the
   *  dispatcher drops — no caller receives them. Absent when there are none. */
  droppedResultKeys?: string[];
}
