//! Circles must tessellate smoothly — the old defaults (angular 0.5 rad,
//! absolute linear 0.1 mm) gave every circle a blocky ~13 segments, and even
//! fewer on small parts. The bridge now scales linear deflection to each
//! shape's size, and the service defaults tightened angular to 0.25 rad.
//! Hermetic: the cylinder fixture is generated by the occt bridge itself.

use converter::convert::convert_step;

fn cylinder_tris(radius: f64, height: f64, lin: f64, ang: f64) -> u64 {
    let dir = std::env::temp_dir().join(format!(
        "carbon-cyl-{radius}-{height}-{}-{}",
        (lin * 1000.0) as u64,
        (ang * 1000.0) as u64
    ));
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("cyl.step");
    let path_str = path.to_str().unwrap();
    assert!(
        occt_bridge::write_test_cylinder(path_str, radius, height),
        "failed to write test cylinder STEP"
    );
    let text = std::fs::read_to_string(path_str).unwrap();
    let conv = convert_step(path_str, &text, lin, ang).expect("convert");
    conv.triangles as u64
}

/// Small circular features on a LONG part are where angular deflection binds:
/// the bbox-scaled linear deflection stays coarse (sized to the long extent),
/// so the circle's segment count falls to the angular floor — 0.5 rad gave a
/// blocky ~13-gon, 0.25 rad keeps >= ~25 segments. This is the user-visible
/// "blocky hole in an elongated part" case.
#[test]
fn quarter_rad_angular_deflection_smooths_small_features_on_long_parts() {
    let coarse = cylinder_tris(1.0, 200.0, 0.1, 0.5);
    let smooth = cylinder_tris(1.0, 200.0, 0.1, 0.25);
    assert!(
        smooth > coarse,
        "0.25 rad should out-tessellate 0.5 rad on a thin long cylinder (got {smooth} vs {coarse})"
    );
    assert!(
        smooth >= 90,
        "thin cylinder at 0.25 rad should have >= ~25 circle segments (got {smooth} tris)"
    );
}

/// A SMALL part must not tessellate coarser than a big one of the same shape:
/// the bridge scales linear deflection to the shape's bbox, so a 2 mm-radius
/// cylinder keeps proportionally as many circle segments as a 50 mm one.
#[test]
fn small_parts_keep_proportional_smoothness() {
    let small = cylinder_tris(2.0, 8.0, 0.1, 0.25);
    let big = cylinder_tris(50.0, 200.0, 0.1, 0.25);
    // Angular deflection dominates both (scale-invariant), so the small
    // cylinder should be within ~2x of the big one's tessellation — not an
    // order of magnitude blockier as with a fixed absolute 0.1 mm sag.
    assert!(
        small * 2 >= big / 2,
        "small cylinder tessellated disproportionately coarse ({small} vs {big} tris)"
    );
    assert!(
        small >= 90,
        "small cylinder should still have >= ~25 circle segments (got {small} tris)"
    );
}
